### ISSUE TITLE
Implement environment settings

### ISSUE THREAD

**Issue by hdubugras** [pagarme/pagarme-php#1]
Should send 'X-Live' or not in the header

**Comment by ricardotulio** [comment]
Hi @hdubugras!

We're closing this PR for the following reasons:

- This version has been deprecated since the release of [version 3.0](https://github.com/pagarme/pagarme-php/releases/tag/v3.0) and any further issues should be focused in the V3 branch. 
- We use the package [GuzzleHttp](http://docs.guzzlephp.org/en/5.3/) for all HTTP requests. You can define all the extra settings for `GuzzleHttp\Client` externally and then inject it into the PagarMe Client, as below:

    ```php
    $guzzleClient = new \GuzzleHttp\Client([
        'defaults' => [
            'headers' => ['Foo' => 'Bar']
        ]
    ]);

    $pagarmeClient = new \PagarMe\Sdk\Client(
        $guzzleClient,
        'MYAWESOMEAPIKEY'
    );
    ```

    You can find more details [in the Guzzle docs](http://docs.guzzlephp.org/en/5.3/clients.html?highlight=default%20options#creating-a-client);
